// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconLeverage({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg viewBox="0 0 8 8" fill="none" width={size} height={size}>
      <path
        d="M1.75896 0.840652L7.44029 0.840571M7.44029 0.840571L7.44029 6.4411M7.44029 0.840571L0.840624 7.44023"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
