// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconLeverageAction({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg viewBox="0 0 16 16" fill="none" width={size} height={size}>
      <path
        d="M5.54706 15.5V7.12256C5.54706 6.69773 5.89146 6.35333 6.31629 6.35333H9.82637C10.2512 6.35333 10.5956 6.69773 10.5956 7.12256V15.5M5.54706 15.5L5.54828 11.8362C5.54843 11.4112 5.20399 11.0667 4.77905 11.0667H1.26923C0.844396 11.0667 0.5 11.4111 0.5 11.8359V14.7308C0.5 15.1556 0.844396 15.5 1.26923 15.5H5.54706ZM5.54706 15.5H10.5956M10.5956 15.5V1.26923C10.5956 0.844396 10.94 0.5 11.3648 0.5H14.7308C15.1556 0.5 15.5 0.844396 15.5 1.26923V14.7308C15.5 15.1556 15.1556 15.5 14.7308 15.5H10.5956Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
