// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconArrowRight({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg viewBox="0 0 12 10" fill="none" width={size} height={size}>
      <path
        d="M6.83333 0.625L11 5M11 5L6.83333 9.375M11 5L1 5"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
