// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconStake({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg viewBox="0 0 12 14" fill="none" width={size} height={size}>
      <path
        d="M2.39995 4.86676V4.25724C2.39995 2.2313 4.00567 0.600098 5.99995 0.600098C7.99424 0.600098 9.59995 2.2313 9.59995 4.25724V4.86676M2.39995 4.86676C1.73995 4.86676 1.19995 5.41534 1.19995 6.08581V12.181C1.19995 12.8515 1.73995 13.4001 2.39995 13.4001H9.59995C10.26 13.4001 10.8 12.8515 10.8 12.181V6.08581C10.8 5.41534 10.26 4.86676 9.59995 4.86676M2.39995 4.86676H9.59995"
        stroke="currentColor"
        strokeLinecap="round"
      />
    </svg>
  );
}
