// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconDashboard({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg viewBox="0 0 14 14" fill="none" width={size} height={size}>
      <path
        d="M1 5.27737C1 5.0311 1.12534 4.80007 1.33638 4.65735L6.53638 1.14078C6.81395 0.953073 7.18605 0.953073 7.46362 1.14078L12.6636 4.65735C12.8747 4.80007 13 5.0311 13 5.27737V11.8588C13 12.4891 12.4627 13 11.8 13H2.2C1.53726 13 1 12.4891 1 11.8588V5.27737Z"
        stroke="currentColor"
      />
    </svg>
  );
}
