// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconArrowFilter({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg viewBox="0 0 6 6" fill="none" width={size} height={size}>
      <path
        d="M5.33335 3.44436L3.00002 5.66659M3.00002 5.66659L0.666687 3.44436M3.00002 5.66659L3.00002 0.333252"
        stroke="currentColor"
        strokeWidth={0.666667}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
