// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconEarnAction({
  size = 24,
}: {
  size?: number;
}) {
  return (
    <svg viewBox="0 0 16 16" fill="none" width={size} height={size}>
      <path
        d="M10.8125 7.99954H8M8 7.99954H5.1875M8 7.99954V10.812M8 7.99954L8 5.18704M15.5 8C15.5 12.1421 12.1421 15.5 8 15.5C3.85786 15.5 0.5 12.1421 0.5 8C0.5 3.85786 3.85786 0.5 8 0.5C12.1421 0.5 15.5 3.85786 15.5 8Z"
        stroke="currentColor"
        strokeLinecap="round"
      />
    </svg>
  );
}
