export const Governance = [
  {
    "type": "constructor",
    "inputs": [
      { "name": "_accel", "type": "address", "internalType": "address" },
      { "name": "_lusd", "type": "address", "internalType": "address" },
      { "name": "_stakingV1", "type": "address", "internalType": "address" },
      { "name": "_usdx", "type": "address", "internalType": "address" },
      {
        "name": "_config",
        "type": "tuple",
        "internalType": "struct IGovernance.Configuration",
        "components": [
          { "name": "registrationFee", "type": "uint256", "internalType": "uint256" },
          { "name": "registrationThresholdFactor", "type": "uint256", "internalType": "uint256" },
          { "name": "unregistrationThresholdFactor", "type": "uint256", "internalType": "uint256" },
          { "name": "unregistrationAfterEpochs", "type": "uint256", "internalType": "uint256" },
          { "name": "votingThresholdFactor", "type": "uint256", "internalType": "uint256" },
          { "name": "minClaim", "type": "uint256", "internalType": "uint256" },
          { "name": "minAccrual", "type": "uint256", "internalType": "uint256" },
          { "name": "epochStart", "type": "uint256", "internalType": "uint256" },
          { "name": "epochDuration", "type": "uint256", "internalType": "uint256" },
          { "name": "epochVotingCutoff", "type": "uint256", "internalType": "uint256" },
        ],
      },
      { "name": "_owner", "type": "address", "internalType": "address" },
      { "name": "_initiatives", "type": "address[]", "internalType": "address[]" },
    ],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "EPOCH_DURATION",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "EPOCH_START",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "EPOCH_VOTING_CUTOFF",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "MIN_ACCRUAL",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "MIN_CLAIM",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "REGISTRATION_FEE",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "REGISTRATION_THRESHOLD_FACTOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "UNREGISTRATION_AFTER_EPOCHS",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "UNREGISTRATION_THRESHOLD_FACTOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "VOTING_THRESHOLD_FACTOR",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "allocateACCEL",
    "inputs": [
      { "name": "_initiativesToReset", "type": "address[]", "internalType": "address[]" },
      { "name": "_initiatives", "type": "address[]", "internalType": "address[]" },
      { "name": "_absoluteACCELVotes", "type": "int256[]", "internalType": "int256[]" },
      { "name": "_absoluteACCELVetos", "type": "int256[]", "internalType": "int256[]" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "usdx",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IERC20" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "usdxAccrued",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "calculateVotingThreshold",
    "inputs": [{ "name": "_votes", "type": "uint256", "internalType": "uint256" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "calculateVotingThreshold",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "claimForInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "claimFromStakingV1",
    "inputs": [{ "name": "_rewardRecipient", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "lusdSent", "type": "uint256", "internalType": "uint256" }, {
      "name": "ethSent",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "deployUserProxy",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositACCEL",
    "inputs": [{ "name": "_accelAmount", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositACCEL",
    "inputs": [{ "name": "_accelAmount", "type": "uint256", "internalType": "uint256" }, {
      "name": "_doSendRewards",
      "type": "bool",
      "internalType": "bool",
    }, { "name": "_recipient", "type": "address", "internalType": "address" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositACCELViaPermit",
    "inputs": [
      { "name": "_accelAmount", "type": "uint256", "internalType": "uint256" },
      {
        "name": "_permitParams",
        "type": "tuple",
        "internalType": "struct PermitParams",
        "components": [
          { "name": "owner", "type": "address", "internalType": "address" },
          { "name": "spender", "type": "address", "internalType": "address" },
          { "name": "value", "type": "uint256", "internalType": "uint256" },
          { "name": "deadline", "type": "uint256", "internalType": "uint256" },
          { "name": "v", "type": "uint8", "internalType": "uint8" },
          { "name": "r", "type": "bytes32", "internalType": "bytes32" },
          { "name": "s", "type": "bytes32", "internalType": "bytes32" },
        ],
      },
      { "name": "_doSendRewards", "type": "bool", "internalType": "bool" },
      { "name": "_recipient", "type": "address", "internalType": "address" },
    ],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "depositACCELViaPermit",
    "inputs": [{ "name": "_accelAmount", "type": "uint256", "internalType": "uint256" }, {
      "name": "_permitParams",
      "type": "tuple",
      "internalType": "struct PermitParams",
      "components": [
        { "name": "owner", "type": "address", "internalType": "address" },
        { "name": "spender", "type": "address", "internalType": "address" },
        { "name": "value", "type": "uint256", "internalType": "uint256" },
        { "name": "deadline", "type": "uint256", "internalType": "uint256" },
        { "name": "v", "type": "uint8", "internalType": "uint8" },
        { "name": "r", "type": "bytes32", "internalType": "bytes32" },
        { "name": "s", "type": "bytes32", "internalType": "bytes32" },
      ],
    }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "deriveUserProxyAddress",
    "inputs": [{ "name": "_user", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "epoch",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "epochStart",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getInitiativeSnapshotAndState",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [{
      "name": "initiativeSnapshot",
      "type": "tuple",
      "internalType": "struct IGovernance.InitiativeVoteSnapshot",
      "components": [
        { "name": "votes", "type": "uint256", "internalType": "uint256" },
        { "name": "forEpoch", "type": "uint256", "internalType": "uint256" },
        { "name": "lastCountedEpoch", "type": "uint256", "internalType": "uint256" },
        { "name": "vetos", "type": "uint256", "internalType": "uint256" },
      ],
    }, {
      "name": "initiativeState",
      "type": "tuple",
      "internalType": "struct IGovernance.InitiativeState",
      "components": [
        { "name": "voteACCEL", "type": "uint256", "internalType": "uint256" },
        { "name": "voteOffset", "type": "uint256", "internalType": "uint256" },
        { "name": "vetoACCEL", "type": "uint256", "internalType": "uint256" },
        { "name": "vetoOffset", "type": "uint256", "internalType": "uint256" },
        { "name": "lastEpochClaim", "type": "uint256", "internalType": "uint256" },
      ],
    }, { "name": "shouldUpdate", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getInitiativeState",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }, {
      "name": "_votesSnapshot",
      "type": "tuple",
      "internalType": "struct IGovernance.VoteSnapshot",
      "components": [{ "name": "votes", "type": "uint256", "internalType": "uint256" }, {
        "name": "forEpoch",
        "type": "uint256",
        "internalType": "uint256",
      }],
    }, {
      "name": "_votesForInitiativeSnapshot",
      "type": "tuple",
      "internalType": "struct IGovernance.InitiativeVoteSnapshot",
      "components": [
        { "name": "votes", "type": "uint256", "internalType": "uint256" },
        { "name": "forEpoch", "type": "uint256", "internalType": "uint256" },
        { "name": "lastCountedEpoch", "type": "uint256", "internalType": "uint256" },
        { "name": "vetos", "type": "uint256", "internalType": "uint256" },
      ],
    }, {
      "name": "_initiativeState",
      "type": "tuple",
      "internalType": "struct IGovernance.InitiativeState",
      "components": [
        { "name": "voteACCEL", "type": "uint256", "internalType": "uint256" },
        { "name": "voteOffset", "type": "uint256", "internalType": "uint256" },
        { "name": "vetoACCEL", "type": "uint256", "internalType": "uint256" },
        { "name": "vetoOffset", "type": "uint256", "internalType": "uint256" },
        { "name": "lastEpochClaim", "type": "uint256", "internalType": "uint256" },
      ],
    }],
    "outputs": [{ "name": "status", "type": "uint8", "internalType": "enum IGovernance.InitiativeStatus" }, {
      "name": "lastEpochClaim",
      "type": "uint256",
      "internalType": "uint256",
    }, { "name": "claimableAmount", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getInitiativeState",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "status", "type": "uint8", "internalType": "enum IGovernance.InitiativeStatus" }, {
      "name": "lastEpochClaim",
      "type": "uint256",
      "internalType": "uint256",
    }, { "name": "claimableAmount", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "getLatestVotingThreshold",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "getTotalVotesAndState",
    "inputs": [],
    "outputs": [{
      "name": "snapshot",
      "type": "tuple",
      "internalType": "struct IGovernance.VoteSnapshot",
      "components": [{ "name": "votes", "type": "uint256", "internalType": "uint256" }, {
        "name": "forEpoch",
        "type": "uint256",
        "internalType": "uint256",
      }],
    }, {
      "name": "state",
      "type": "tuple",
      "internalType": "struct IGovernance.GlobalState",
      "components": [{ "name": "countedVoteACCEL", "type": "uint256", "internalType": "uint256" }, {
        "name": "countedVoteOffset",
        "type": "uint256",
        "internalType": "uint256",
      }],
    }, { "name": "shouldUpdate", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "globalState",
    "inputs": [],
    "outputs": [{ "name": "countedVoteACCEL", "type": "uint256", "internalType": "uint256" }, {
      "name": "countedVoteOffset",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "initiativeStates",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [
      { "name": "voteACCEL", "type": "uint256", "internalType": "uint256" },
      { "name": "voteOffset", "type": "uint256", "internalType": "uint256" },
      { "name": "vetoACCEL", "type": "uint256", "internalType": "uint256" },
      { "name": "vetoOffset", "type": "uint256", "internalType": "uint256" },
      { "name": "lastEpochClaim", "type": "uint256", "internalType": "uint256" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "isOwner",
    "inputs": [],
    "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "accel",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IERC20" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "accelAllocatedByUserToInitiative",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }, {
      "name": "",
      "type": "address",
      "internalType": "address",
    }],
    "outputs": [
      { "name": "voteACCEL", "type": "uint256", "internalType": "uint256" },
      { "name": "voteOffset", "type": "uint256", "internalType": "uint256" },
      { "name": "vetoACCEL", "type": "uint256", "internalType": "uint256" },
      { "name": "vetoOffset", "type": "uint256", "internalType": "uint256" },
      { "name": "atEpoch", "type": "uint256", "internalType": "uint256" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "accelToVotes",
    "inputs": [{ "name": "_accelAmount", "type": "uint256", "internalType": "uint256" }, {
      "name": "_timestamp",
      "type": "uint256",
      "internalType": "uint256",
    }, { "name": "_offset", "type": "uint256", "internalType": "uint256" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "pure",
  },
  {
    "type": "function",
    "name": "multiDelegateCall",
    "inputs": [{ "name": "inputs", "type": "bytes[]", "internalType": "bytes[]" }],
    "outputs": [{ "name": "returnValues", "type": "bytes[]", "internalType": "bytes[]" }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "registerInitialInitiatives",
    "inputs": [{ "name": "_initiatives", "type": "address[]", "internalType": "address[]" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "registerInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "registeredInitiatives",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "resetAllocations",
    "inputs": [{ "name": "_initiativesToReset", "type": "address[]", "internalType": "address[]" }, {
      "name": "checkAll",
      "type": "bool",
      "internalType": "bool",
    }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "secondsWithinEpoch",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "snapshotVotesForInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [{
      "name": "voteSnapshot",
      "type": "tuple",
      "internalType": "struct IGovernance.VoteSnapshot",
      "components": [{ "name": "votes", "type": "uint256", "internalType": "uint256" }, {
        "name": "forEpoch",
        "type": "uint256",
        "internalType": "uint256",
      }],
    }, {
      "name": "initiativeVoteSnapshot",
      "type": "tuple",
      "internalType": "struct IGovernance.InitiativeVoteSnapshot",
      "components": [
        { "name": "votes", "type": "uint256", "internalType": "uint256" },
        { "name": "forEpoch", "type": "uint256", "internalType": "uint256" },
        { "name": "lastCountedEpoch", "type": "uint256", "internalType": "uint256" },
        { "name": "vetos", "type": "uint256", "internalType": "uint256" },
      ],
    }],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "stakingV1",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "contract IACCELStaking" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "unregisterInitiative",
    "inputs": [{ "name": "_initiative", "type": "address", "internalType": "address" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "userProxyImplementation",
    "inputs": [],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "userStates",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [
      { "name": "unallocatedACCEL", "type": "uint256", "internalType": "uint256" },
      { "name": "unallocatedOffset", "type": "uint256", "internalType": "uint256" },
      { "name": "allocatedACCEL", "type": "uint256", "internalType": "uint256" },
      { "name": "allocatedOffset", "type": "uint256", "internalType": "uint256" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "votesForInitiativeSnapshot",
    "inputs": [{ "name": "", "type": "address", "internalType": "address" }],
    "outputs": [
      { "name": "votes", "type": "uint256", "internalType": "uint256" },
      { "name": "forEpoch", "type": "uint256", "internalType": "uint256" },
      { "name": "lastCountedEpoch", "type": "uint256", "internalType": "uint256" },
      { "name": "vetos", "type": "uint256", "internalType": "uint256" },
    ],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "votesSnapshot",
    "inputs": [],
    "outputs": [{ "name": "votes", "type": "uint256", "internalType": "uint256" }, {
      "name": "forEpoch",
      "type": "uint256",
      "internalType": "uint256",
    }],
    "stateMutability": "view",
  },
  {
    "type": "function",
    "name": "withdrawACCEL",
    "inputs": [{ "name": "_accelAmount", "type": "uint256", "internalType": "uint256" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "function",
    "name": "withdrawACCEL",
    "inputs": [{ "name": "_accelAmount", "type": "uint256", "internalType": "uint256" }, {
      "name": "_doSendRewards",
      "type": "bool",
      "internalType": "bool",
    }, { "name": "_recipient", "type": "address", "internalType": "address" }],
    "outputs": [],
    "stateMutability": "nonpayable",
  },
  {
    "type": "event",
    "name": "AllocateACCEL",
    "inputs": [
      { "name": "user", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "initiative", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "deltaVoteACCEL", "type": "int256", "indexed": false, "internalType": "int256" },
      { "name": "deltaVetoACCEL", "type": "int256", "indexed": false, "internalType": "int256" },
      { "name": "atEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "hookSuccess", "type": "bool", "indexed": false, "internalType": "bool" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "ClaimForInitiative",
    "inputs": [
      { "name": "initiative", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "usdx", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "forEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "hookSuccess", "type": "bool", "indexed": false, "internalType": "bool" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "DeployUserProxy",
    "inputs": [{ "name": "user", "type": "address", "indexed": true, "internalType": "address" }, {
      "name": "userProxy",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "DepositACCEL",
    "inputs": [
      { "name": "user", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "rewardRecipient", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "accelAmount", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "lusdReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "lusdSent", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "ethReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "ethSent", "type": "uint256", "indexed": false, "internalType": "uint256" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [{ "name": "previousOwner", "type": "address", "indexed": true, "internalType": "address" }, {
      "name": "newOwner",
      "type": "address",
      "indexed": true,
      "internalType": "address",
    }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "RegisterInitiative",
    "inputs": [
      { "name": "initiative", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "registrant", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "atEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "hookSuccess", "type": "bool", "indexed": false, "internalType": "bool" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "SnapshotVotes",
    "inputs": [{ "name": "votes", "type": "uint256", "indexed": false, "internalType": "uint256" }, {
      "name": "forEpoch",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256",
    }, { "name": "usdxAccrued", "type": "uint256", "indexed": false, "internalType": "uint256" }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "SnapshotVotesForInitiative",
    "inputs": [
      { "name": "initiative", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "votes", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "vetos", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "forEpoch", "type": "uint256", "indexed": false, "internalType": "uint256" },
    ],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "UnregisterInitiative",
    "inputs": [{ "name": "initiative", "type": "address", "indexed": false, "internalType": "address" }, {
      "name": "atEpoch",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256",
    }, { "name": "hookSuccess", "type": "bool", "indexed": false, "internalType": "bool" }],
    "anonymous": false,
  },
  {
    "type": "event",
    "name": "WithdrawACCEL",
    "inputs": [
      { "name": "user", "type": "address", "indexed": true, "internalType": "address" },
      { "name": "recipient", "type": "address", "indexed": false, "internalType": "address" },
      { "name": "accelReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "accelSent", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "lusdReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "lusdSent", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "ethReceived", "type": "uint256", "indexed": false, "internalType": "uint256" },
      { "name": "ethSent", "type": "uint256", "indexed": false, "internalType": "uint256" },
    ],
    "anonymous": false,
  },
  {
    "type": "error",
    "name": "AddressEmptyCode",
    "inputs": [{ "name": "target", "type": "address", "internalType": "address" }],
  },
  {
    "type": "error",
    "name": "AddressInsufficientBalance",
    "inputs": [{ "name": "account", "type": "address", "internalType": "address" }],
  },
  { "type": "error", "name": "ERC1167FailedCreateClone", "inputs": [] },
  { "type": "error", "name": "FailedInnerCall", "inputs": [] },
  { "type": "error", "name": "ReentrancyGuardReentrantCall", "inputs": [] },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [{ "name": "token", "type": "address", "internalType": "address" }],
  },
] as const;
